sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.8

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require wp-coding-standards/wpcs
  - composer global require phpcompatibility/phpcompatibility-wp
  - composer global require dealerdirect/phpcodesniffer-composer-installer
  - composer global require sirbrillig/phpcs-variable-analysis
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpcs
  - phpunit
